# Generated by Django 5.2.14 on 2026-05-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_fix_profile_pic_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="login_id",
            field=models.CharField(
                blank=True,
                help_text="Unique ID for staff/student login. Leave blank for admin (uses email).",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
