# Generated by Django 5.2.14 on 2026-05-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0027_leaderboardseason_leaderboardsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularyday",
            name="release_scope",
            field=models.CharField(
                choices=[("group", "Assigned group only"), ("all", "All students")],
                default="group",
                help_text="Who can see this vocabulary day after it is released.",
                max_length=10,
            ),
        ),
    ]
