# Generated by Django 6.0.5 on 2026-06-04 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_threads_for_existing_groups(apps, schema_editor):
    Group = apps.get_model("main_app", "Group")
    ChatThread = apps.get_model("main_app", "ChatThread")
    existing_group_ids = set(ChatThread.objects.values_list("group_id", flat=True))
    ChatThread.objects.bulk_create(
        [
            ChatThread(group_id=group_id)
            for group_id in Group.objects.exclude(id__in=existing_group_ids).values_list(
                "id", flat=True
            )
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0029_add_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_thread",
                        to="main_app.group",
                    ),
                ),
            ],
            options={
                "ordering": ["group__name"],
            },
        ),
        migrations.CreateModel(
            name="ChatReadState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_read_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to="main_app.chatthread",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_threads_for_existing_groups, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="main_app.chatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["updated_at"], name="main_app_ch_updated_825443_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatreadstate",
            index=models.Index(
                fields=["user", "thread"], name="main_app_ch_user_id_d75f1d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatreadstate",
            unique_together={("thread", "user")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["thread", "created_at"], name="main_app_ch_thread__6e90a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="main_app_ch_sender__59fd77_idx"
            ),
        ),
    ]
