# Generated by Django 6.0.5 on 2026-06-05 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0030_chatthread_chatreadstate_chatmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationLead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=160)),
                ("first_name", models.CharField(blank=True, default="", max_length=80)),
                ("last_name", models.CharField(blank=True, default="", max_length=80)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                (
                    "parent_phone",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("program", models.CharField(blank=True, default="", max_length=140)),
                ("branch", models.CharField(blank=True, default="", max_length=140)),
                (
                    "preferred_schedule",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "source",
                    models.CharField(blank=True, default="website", max_length=80),
                ),
                (
                    "social_handle",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("campaign", models.CharField(blank=True, default="", max_length=160)),
                (
                    "utm_source",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "utm_campaign",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("referrer", models.CharField(blank=True, default="", max_length=500)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "remote_addr",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_registration_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="main_app_re_status_e37eaf_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="main_app_re_source_538db7_idx",
                    ),
                    models.Index(fields=["phone"], name="main_app_re_phone_3088bb_idx"),
                    models.Index(fields=["email"], name="main_app_re_email_31da8f_idx"),
                ],
            },
        ),
    ]
