# Generated by Django 6.0.5 on 2026-06-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0031_registrationlead"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="branches",
            field=models.ManyToManyField(
                blank=True,
                help_text="Branches this admin manages. Ignored when is_super_admin is True.",
                related_name="admins",
                to="main_app.branch",
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_super_admin",
            field=models.BooleanField(
                default=True,
                help_text="Super admins see every branch. Branch admins see only their assigned branches.",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="main_app.branch",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="main_app.branch",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["group", "is_active"], name="main_app_en_group_i_1c15ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "is_active"], name="main_app_en_student_bcef2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["branch", "is_archived"], name="main_app_gr_branch__288d44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["teacher", "is_archived"], name="main_app_gr_teacher_dfda95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["branch", "is_active"], name="main_app_st_branch__efaec0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["course", "is_active"], name="main_app_st_course__db2081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["branch", "status"], name="main_app_st_branch__a24377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["course", "status"], name="main_app_st_course__4353a4_idx"
            ),
        ),
    ]
