# Generated by Django 6.0.5 on 2026-06-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0036_merge_20260610_2258"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="app_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mobile app preferences (accent colour, font size, language, notification toggles).",
            ),
        ),
    ]
