# Generated by Django 3.1.1 on 2026-05-12 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('due_on', models.DateField(default=main_app.models._default_loan_due_date)),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('fine_paid', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='main_app.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='main_app.student')),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(returned_on__isnull=True), fields=('student', 'book'), name='one_active_loan_per_student_book'),
        ),
    ]
