# Generated by Django 3.1.1 on 2026-05-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_attendance_unique_group_subject_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssuedBook',
        ),
        migrations.RemoveField(
            model_name='library',
            name='book',
        ),
        migrations.RemoveField(
            model_name='library',
            name='student',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (-1, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (-1, 'Rejected')], default=0),
        ),
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['student'], name='main_app_at_student_1c078c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['attendance'], name='main_app_at_attenda_6b9398_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='main_app_en_student_c3f63f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['group'], name='main_app_en_group_i_8023db_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['student'], name='main_app_lo_student_50ef19_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['returned_on'], name='main_app_lo_returne_1396b8_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course'], name='main_app_su_course__daf82b_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['staff'], name='main_app_su_staff_i_64d1b3_idx'),
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
