# Generated by Django 3.1.1 on 2026-05-15 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_cleanup_legacy_models_add_indexes_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('result', 'Result'), ('announcement', 'Announcement'), ('homework', 'Homework'), ('general', 'General')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject',
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.CharField(blank=True, default='', help_text='Classroom or room number, e.g. Room 3A', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization',
            field=models.CharField(blank=True, default='', help_text='e.g. IELTS, Mathematics, Business English', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        # Deduplicate attendance rows before applying the tighter (group, date) constraint.
        # Old constraint was (group, subject, date) where subject was always NULL,
        # so SQLite may have stored multiple rows per group+date. Keep the lowest-id row.
        # Step 1: delete AttendanceReport rows pointing at the duplicate Attendance rows.
        migrations.RunSQL(
            sql="""
                DELETE FROM main_app_attendancereport
                WHERE attendance_id NOT IN (
                    SELECT MIN(id) FROM main_app_attendance
                    GROUP BY group_id, date
                )
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: delete the duplicate Attendance rows themselves.
        migrations.RunSQL(
            sql="""
                DELETE FROM main_app_attendance
                WHERE id NOT IN (
                    SELECT MIN(id) FROM main_app_attendance
                    GROUP BY group_id, date
                )
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('group', 'date')},
        ),
        migrations.DeleteModel(
            name='NotificationStaff',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='main_app_no_recipie_f0219c_idx'),
        ),
    ]
