# Generated by Django 5.2.14 on 2026-05-16 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0020_populate_login_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=200)),
                ("definition", models.TextField()),
                ("example_sentence", models.TextField(blank=True, default="")),
                (
                    "translation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Native-language translation (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. noun, verb, adjective",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vocabulary_words",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to make visible to all students",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vocabulary",
                        to="main_app.group",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vocabulary",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VocabularyProgress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Learning"),
                            (2, "Review"),
                            (3, "Mastered"),
                        ],
                        default=0,
                    ),
                ),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("incorrect_count", models.PositiveIntegerField(default=0)),
                ("interval_days", models.PositiveIntegerField(default=1)),
                (
                    "next_review_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_progress",
                        to="main_app.student",
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="main_app.vocabulary",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "vocabulary")},
            },
        ),
    ]
