# Generated by Django 5.2.14 on 2026-05-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0021_vocabulary_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_english",
            field=models.BooleanField(
                default=False,
                help_text="Mark as English program to enable level tracking and vocabulary features.",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Level 1"),
                    (2, "Level 2"),
                    (3, "Level 3"),
                    (4, "Level 4"),
                    (5, "Level 5"),
                    (6, "Level 6"),
                ],
                help_text="English proficiency level (1–6). Only applies to English-program students.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "All Levels"),
                    (1, "Level 1"),
                    (2, "Level 2"),
                    (3, "Level 3"),
                    (4, "Level 4"),
                    (5, "Level 5"),
                    (6, "Level 6"),
                ],
                default=0,
                help_text='Target student level. "All Levels" means visible to every English student.',
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to share with all groups at this level",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vocabulary",
                to="main_app.group",
            ),
        ),
    ]
