# Generated by Django 5.2.14 on 2026-05-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0023_vocabulary_day_system"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vocabularyday",
            name="unique_group_day",
        ),
        migrations.AddField(
            model_name="group",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="The date when this group starts classes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="theme",
            field=models.CharField(
                choices=[
                    ("dark", "Dark"),
                    ("bright", "Bright"),
                    ("system", "System Default"),
                ],
                default="system",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vocabularyday",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Private teaching notes (not shown to students).",
            ),
        ),
        migrations.AlterField(
            model_name="vocabularydayword",
            name="pronunciation_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IPA or phonetic hint, e.g. /ˈɛfərt/",
                max_length=300,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vocabularyday",
            unique_together={("group", "day_number")},
        ),
    ]
