# Generated by Django 5.2.14 on 2026-05-17 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0025_remove_vocabulary_add_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardStory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="stories/"),
                ),
                (
                    "story_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("vocab", "Vocabulary Tip"),
                            ("event", "Event"),
                            ("tip", "Study Tip"),
                            ("challenge", "Challenge"),
                            ("update", "Teacher Update"),
                        ],
                        default="announcement",
                        max_length=20,
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        default="📢",
                        help_text="Emoji shown when no image is uploaded",
                        max_length=8,
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        blank=True,
                        default="#0C1F45",
                        help_text="Card background colour (hex) used when no image",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Story is hidden after this date/time",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to show to all students",
                        to="main_app.group",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
