# Generated by Django 5.2.14 on 2026-05-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0026_dashboard_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardSeason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text='e.g. "October 2026"', max_length=120),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="monthly",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for ongoing season",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Snapshots are only captured for active seasons",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LeaderboardSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_weight", models.PositiveSmallIntegerField(default=25)),
                ("homework_weight", models.PositiveSmallIntegerField(default=25)),
                ("quizzes_weight", models.PositiveSmallIntegerField(default=25)),
                ("results_weight", models.PositiveSmallIntegerField(default=25)),
                ("enable_attendance", models.BooleanField(default=True)),
                ("enable_homework", models.BooleanField(default=True)),
                ("enable_quizzes", models.BooleanField(default=True)),
                ("enable_results", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leaderboard Settings",
                "verbose_name_plural": "Leaderboard Settings",
            },
        ),
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("score", models.FloatField()),
                ("attendance_pct", models.FloatField(blank=True, null=True)),
                ("homework_pct", models.FloatField(blank=True, null=True)),
                ("quizzes_pct", models.FloatField(blank=True, null=True)),
                ("results_pct", models.FloatField(blank=True, null=True)),
                ("badge", models.CharField(blank=True, default="", max_length=60)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="main_app.leaderboardseason",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_snapshots",
                        to="main_app.student",
                    ),
                ),
            ],
            options={
                "ordering": ["season", "rank"],
                "indexes": [
                    models.Index(
                        fields=["season", "rank"], name="main_app_le_season__6cdb2c_idx"
                    ),
                    models.Index(
                        fields=["student", "season"],
                        name="main_app_le_student_54b16b_idx",
                    ),
                ],
                "unique_together": {("season", "student")},
            },
        ),
    ]
