# Generated by Django 5.2.14 on 2026-05-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0028_add_vocabulary_release_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Date of birth (YYYY-MM-DD). Used to generate the user's login ID.",
                null=True,
            ),
        ),
    ]
