# Generated by Django 6.0.5 on 2026-06-10 06:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0033_backfill_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Default monthly tuition in UZS soʻm. Groups may override this.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Monthly tuition in UZS soʻm for this group. Leave blank to use the course fee.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("attendance", "Attendance"),
                    ("result", "Result"),
                    ("announcement", "Announcement"),
                    ("homework", "Homework"),
                    ("vocabulary", "Vocabulary"),
                    ("payment", "Payment"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="First day of the month this invoice covers."
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Discount in UZS soʻm subtracted from the amount.",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "Due"),
                            ("partial", "Partially paid"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="due",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField()),
                ("note", models.TextField(blank=True, default="")),
                ("last_reminded_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="main_app.group",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="main_app.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card terminal"),
                            ("transfer", "Bank transfer"),
                            ("payme", "Payme"),
                            ("click", "Click"),
                            ("uzum", "Uzum"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("paid_on", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="main_app.invoice",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["student", "status"], name="main_app_in_student_32166f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["group", "period"], name="main_app_in_group_i_3444d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "due_date"], name="main_app_in_status_6652f6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", False)),
                fields=("student", "group", "period"),
                name="one_invoice_per_student_group_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", 0), ("amount__gte", 0)),
                name="invoice_amounts_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice"], name="main_app_pa_invoice_08681f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["paid_on"], name="main_app_pa_paid_on_020fe9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
    ]
