# Generated by Django 5.2.15 on 2026-06-10 12:15

import django.core.validators
from django.db import migrations, models


def clamp_existing_scores(apps, schema_editor):
    """Bring legacy rows into the test≤40 / exam≤60 grading scale."""
    StudentResult = apps.get_model("main_app", "StudentResult")
    for row in StudentResult.objects.filter(models.Q(test__gt=40) | models.Q(exam__gt=60)):
        row.test = min(max(row.test, 0), 40)
        row.exam = min(max(row.exam, 0), 60)
        row.save(update_fields=["test", "exam"])


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0033_backfill_branch"),
    ]

    operations = [
        migrations.RunPython(clamp_existing_scores, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="studentresult",
            name="exam",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="test",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
    ]
