# Generated by Django 5.2.15 on 2026-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0034_alter_studentresult_exam_alter_studentresult_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_attachments/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="attachment_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
    ]
