# Generated by Django 5.2.15 on 2026-06-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0034_course_monthly_fee_group_monthly_fee_and_more"),
        (
            "main_app",
            "0035_chatmessage_attachment_chatmessage_attachment_name_and_more",
        ),
    ]

    operations = []
